services:
  - type: web
    name: fb-job-tracker
    runtime: docker
    repo: https://github.com/frograiny/FB-Job-Tracker-Matcher
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
